# Generated by Django 4.1.7 on 2023-03-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Пленки'},
        ),
    ]
